### ISSUE TITLE
Missing setting 'region' on Openstack

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-community-attic/inception-server#8]
When running `bundle exec inception deploy` with the current master I get the following: `'missing_key': Missing setting 'region' in  (ReadWriteSettings::MissingSetting)`

``` bash
Using your git user.name (Ruben Koster)
Acquiring a public IP address... /Users/rubenkoster/.rvm/gems/ruby-1.9.3-p194@if-bosh/gems/readwritesettings-3.0.1/lib/readwritesettings.rb:244:in `missing_key': Missing setting 'region' in  (ReadWriteSettings::MissingSetting)
        from /Users/rubenkoster/.rvm/gems/ruby-1.9.3-p194@if-bosh/gems/readwritesettings-3.0.1/lib/readwritesettings.rb:117:in `method_missing'
        from /Users/rubenkoster/.rvm/gems/ruby-1.9.3-p194@if-bosh/bundler/gems/inception-server-ba1192e984c6/lib/inception/providers/clients/openstack_provider_client.rb:56:in `setup_fog_connection'
        from /Users/rubenkoster/.rvm/gems/ruby-1.9.3-p194@if-bosh/bundler/gems/inception-server-ba1192e984c6/lib/inception/providers/clients/fog_provider_client.rb:13:in `initialize'
        from /Users/rubenkoster/.rvm/gems/ruby-1.9.3-p194@if-bosh/bundler/gems/inception-server-ba1192e984c6/lib/inception/providers.rb:22:in `new'
        from /Users/rubenkoster/.rvm/gems/ruby-1.9.3-p194@if-bosh/bundler/gems/inception-server-ba1192e984c6/lib/inception/providers.rb:22:in `provider_client'
        from /Users/rubenkoster/.rvm/gems/ruby-1.9.3-p194@if-bosh/bundler/gems/inception-server-ba1192e984c6/lib/inception/cli_helpers/provider.rb:5:in `provider_client'
        from /Users/rubenkoster/.rvm/gems/ruby-1.9.3-p194@if-bosh/bundler/gems/inception-server-ba1192e984c6/lib/inception/cli_helpers/prepare_deploy_settings.rb:19:in `provision_or_reuse_public_ip_address_for_inception'
```

My settings file looks like this `cat ~/.inception_server/settings.yml`

``` yaml

---
provider:
  name: openstack
  credentials:
    provider: OpenStack
    openstack_username: {username}
    openstack_api_key: {pw}
    openstack_tenant: {tenant}
    openstack_auth_url: http://{ip}/keystone/v2.0/tokens
    openstack_region:
git:
  name: Ruben Koster
  email: {email}
```
